const projects = [
  {
    id: 1,
    title: "E-commerce Platform",
    description: "A full-stack e-commerce solution with user authentication, product management, shopping cart, and payment integration using Stripe.",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Redux", "Stripe API"],
    image: "https://placehold.co/600x400/3b82f6/ffffff?text=E-commerce+Platform",
    github_link: "https://github.com/yourusername/ecommerce-platform",
    preview_link: "https://ecommerce-demo.example.com",
    featured: true,
    completed: true,
    date: "2024-01-15",
    year: 2024
  },
  {
    id: 2,
    title: "Weather Dashboard",
    description: "Real-time weather application that provides current conditions and forecasts for any location worldwide using OpenWeather API.",
    technologies: ["JavaScript", "HTML5", "CSS3", "OpenWeather API", "Chart.js"],
    image: "https://placehold.co/600x400/06b6d4/ffffff?text=Weather+Dashboard",
    github_link: "https://github.com/yourusername/weather-dashboard",
    preview_link: "https://weather-app-demo.example.com",
    featured: true,
    completed: true,
    date: "2023-11-20",
    year: 2022
  },
  {
    id: 3,
    title: "Task Management System",
    description: "A Kanban-style task management application with drag-and-drop functionality, task assignments, due dates, and progress tracking.",
    technologies: ["Vue.js", "Firebase", "Vuex", "Tailwind CSS", "Drag & Drop API"],
    image: "https://placehold.co/600x400/22c55e/ffffff?text=Task+Management",
    github_link: "https://github.com/yourusername/task-management",
    preview_link: "https://tasks-demo.example.com",
    featured: false,
    completed: true,
    date: "2023-09-05",
    year: 2025
  },
  {
    id: 4,
    title: "Recipe Finder",
    description: "Web application that helps users find recipes based on ingredients they have at home, dietary restrictions, and cuisine preferences.",
    technologies: ["React", "Spoonacular API", "CSS Modules", "Context API"],
    image: "https://placehold.co/600x400/eab308/ffffff?text=Recipe+Finder",
    github_link: "https://github.com/yourusername/recipe-finder",
    preview_link: "https://recipe-finder-demo.example.com",
    featured: false,
    completed: true,
    date: "2023-07-12",
    year: 2023
  },
  {
    id: 5,
    title: "Portfolio Website",
    description: "Personal portfolio website built with SvelteKit showcasing projects, skills, and contact information with a modern and responsive design.",
    technologies: ["SvelteKit", "CSS3", "GitHub Pages", "Responsive Design"],
    image: "https://placehold.co/600x400/a855f7/ffffff?text=Portfolio+Website",
    github_link: "https://github.com/yourusername/portfolio",
    preview_link: "https://portfolio-demo.example.com",
    featured: true,
    completed: false,
    date: "2024-03-01",
    year: 2024
  },
  {
    id: 6,
    title: "Blockchain Explorer",
    description: "A tool to explore blockchain transactions, addresses, and smart contracts with visualization of network activity and real-time updates.",
    technologies: ["TypeScript", "Web3.js", "React", "D3.js", "Ethereum API"],
    image: "https://placehold.co/600x400/ec4899/ffffff?text=Blockchain+Explorer",
    github_link: "https://github.com/yourusername/blockchain-explorer",
    preview_link: "https://blockchain-demo.example.com",
    featured: false,
    completed: false,
    date: "2024-02-18",
    year: 2022
  },
  {
    id: 7,
    title: "Social Media Dashboard",
    description: "Unified dashboard to manage and analyze multiple social media accounts with content scheduling, analytics, and engagement tracking.",
    technologies: ["Angular", "Node.js", "Express", "PostgreSQL", "Social Media APIs"],
    image: "https://placehold.co/600x400/f43f5e/ffffff?text=Social+Media+Dashboard",
    github_link: "https://github.com/yourusername/social-dashboard",
    preview_link: "https://social-dash-demo.example.com",
    featured: true,
    completed: true,
    date: "2023-08-28",
    year: 2023
  },
  {
    id: 8,
    title: "Budget Tracker",
    description: "Personal finance application that helps users track income, expenses, and savings goals with visualization of spending patterns and budget categories.",
    technologies: ["React Native", "Firebase", "Redux", "Victory Charts"],
    image: "https://placehold.co/600x400/14b8a6/ffffff?text=Budget+Tracker",
    github_link: "https://github.com/yourusername/budget-tracker",
    preview_link: "https://budget-app-demo.example.com",
    featured: false,
    completed: true,
    date: "2023-10-11",
    year: 2023
  },
  {
    id: 9,
    title: "AI Image Generator",
    description: "Web application that uses machine learning to generate unique images based on text prompts or style transfers from existing images.",
    technologies: ["Python", "Flask", "TensorFlow", "React", "WebGL"],
    image: "https://placehold.co/600x400/8b5cf6/ffffff?text=AI+Image+Generator",
    github_link: "https://github.com/yourusername/ai-image-generator",
    preview_link: "https://ai-image-demo.example.com",
    featured: true,
    completed: false,
    date: "2024-01-30",
    year: 2021
  },
  {
    id: 10,
    title: "Fitness Tracker",
    description: "Mobile application for tracking workouts, nutrition, and fitness progress with personalized recommendations and achievement badges.",
    technologies: ["Flutter", "Firebase", "Provider", "Google Fit API", "Apple HealthKit"],
    image: "https://placehold.co/600x400/10b981/ffffff?text=Fitness+Tracker",
    github_link: "https://github.com/yourusername/fitness-tracker",
    preview_link: "https://fitness-app-demo.example.com",
    featured: false,
    completed: true,
    date: "2023-12-05",
    year: 2023
  },
  {
    id: 11,
    title: "Language Learning Platform",
    description: "Interactive platform for learning languages with speech recognition, vocabulary tracking, grammar exercises, and conversational practice.",
    technologies: ["Next.js", "MongoDB", "Web Speech API", "Socket.io", "Auth0"],
    image: "https://placehold.co/600x400/f59e0b/ffffff?text=Language+Learning",
    github_link: "https://github.com/yourusername/language-learning",
    preview_link: "https://language-platform-demo.example.com",
    featured: true,
    completed: false,
    date: "2024-02-25",
    year: 2024
  },
  {
    id: 12,
    title: "Real Estate Marketplace",
    description: "Platform connecting buyers, sellers, and real estate agents with property listings, virtual tours, mortgage calculators, and neighborhood analytics.",
    technologies: ["React", "Django", "PostgreSQL", "Google Maps API", "ThreeJS"],
    image: "https://placehold.co/600x400/ef4444/ffffff?text=Real+Estate+Marketplace",
    github_link: "https://github.com/yourusername/real-estate-platform",
    preview_link: "https://realestate-demo.example.com",
    featured: false,
    completed: true,
    date: "2023-11-08",
    year: 2023
  },
  {
    id: 13,
    title: "Podcast Streaming App",
    description: "Audio streaming platform for podcasts with subscription management, offline listening, custom playlists, and personalized recommendations.",
    technologies: ["React Native", "Node.js", "GraphQL", "AWS Amplify", "Audio API"],
    image: "https://placehold.co/600x400/0284c7/ffffff?text=Podcast+App",
    github_link: "https://github.com/yourusername/podcast-app",
    preview_link: "https://podcast-app-demo.example.com",
    featured: true,
    completed: true,
    date: "2023-09-30",
    year: 2023
  },
  {
    id: 14,
    title: "Multiplayer Game",
    description: "Browser-based multiplayer strategy game with real-time interactions, custom avatars, leaderboards, and in-game chat functionality.",
    technologies: ["Phaser.js", "Socket.io", "Node.js", "MongoDB", "WebGL"],
    image: "https://placehold.co/600x400/7c3aed/ffffff?text=Multiplayer+Game",
    github_link: "https://github.com/yourusername/multiplayer-game",
    preview_link: "https://game-demo.example.com",
    featured: false,
    completed: false,
    date: "2024-03-15",
    year: 2024
  },
  {
    id: 15,
    title: "Code Learning Platform",
    description: "Interactive platform for learning programming with code challenges, real-time code execution, progress tracking, and mentorship connections.",
    technologies: ["Vue.js", "Express", "Docker", "Judge0 API", "PostgreSQL"],
    image: "https://placehold.co/600x400/d946ef/ffffff?text=Code+Learning",
    github_link: "https://github.com/yourusername/code-learning-platform",
    preview_link: "https://code-learning-demo.example.com",
    featured: true,
    completed: false,
    date: "2024-01-20",
    year: 2024
  },
  {
    id: 16,
    title: "Automated Job Tracker",
    description: "Application for job seekers to track applications, schedule interviews, and manage follow-ups with analytics on application success rates.",
    technologies: ["React", "Firebase", "Material UI", "Google Calendar API"],
    image: "https://placehold.co/600x400/0ea5e9/ffffff?text=Job+Tracker",
    github_link: "https://github.com/yourusername/job-tracker",
    preview_link: "https://job-tracker-demo.example.com",
    featured: false,
    completed: true,
    date: "2023-10-15",
    year: 2023
  }
]

export default projects;